### ISSUE TITLE
Unable to close connection

### ISSUE THREAD

**Issue by Gaurav-Ambasta** [michalkow/node-mysql-model#11]
Hello, 

I was wondering what would be the right way to close connection in node-mysql-model.

I have tried both the options as mentioned below but it didn't work:
connection.end(function(err) {
  // The connection is terminated now
});

connection.destroy();

Please suggest how we can close the connection.

**Comment by michalkow** [comment]
Hi,

Could you try something like:

```
var MyAppModel = mysqlModel.createConnection({
  host     : 'database-host',
  user     : 'database-user',
  password : 'database-password',
  database : 'database-name',
});

MyAppModel.killConnection(function() {
  console.log('connection closed');
});
```

**Comment by Gaurav-Ambasta** [comment]
Tried but does seem to be working. 

TypeError: this.mySqlConnection.killConnection is not a function
    at UserCatalogRouter.insertItemIntoCatalog (/Users/ambasta/arrakis/dist/gateway/catalog/userCatalog/userCatalogRouter.js:76:38)

**Comment by Gaurav-Ambasta** [comment]
can you please help me with a solution to close the connection ?

**Comment by michalkow** [comment]
Sorry, actually it should be called from model:

```
var MyAppModel = mysqlModel.createConnection({
  host     : 'database-host',
  user     : 'database-user',
  password : 'database-password',
  database : 'database-name',
});

movie = new MyAppModel({tableName: "movies"});

movie.killConnection(function(err) {
  console.log('connection closed');
});
```
