### ISSUE TITLE
Updated fields not returned.

### ISSUE THREAD

**Issue by kpatel1989** [michalkow/node-mysql-model#14]
`var q = "INSERT INTO "+tableName+" SET "+ connection.escape(this.attributes);
					connection.query(q, function(err, result) {
						if(callback){
							callback(err, result);
						}
					});`
Looking at this part of the code in mysql-model.js
It seems like once it inserts the data it doesnt return me the update fields in response. Generally there is a third parameter to the callback which gives the fieldValues from the table and i suppose that needs to be set into the model attributes.

**Comment by michalkow** [comment]
I moved the project to a new repo: https://github.com/michalkow/node-mysql-backbone
Please check the new code and see if the issues persist.
