### ISSUE TITLE
Mysql connection status

### ISSUE THREAD

**Issue by ruudboon** [michalkow/node-mysql-model#17]
Is possible to have feedback if the mysql connection failed?

**Comment by RachedM** [comment]
Yes. you want add "debug: true".

const connection = mysql.createConnection({
	host:'HOST',
	user:'USER', 
	password :'PASS',
	database:'DB', 	
	debug: true, 
	}

in the end you see the message from SSH console

**Comment by michalkow** [comment]
I moved the project to a new repo: https://github.com/michalkow/node-mysql-backbone
I separated Model and Collection code from node-mysql library.
