### ISSUE TITLE
Getting ER_ACCESS_DENIED_ERROR while I am able to connect by simple mysql module for node.

### ISSUE THREAD

**Issue by puneetthakur66** [michalkow/node-mysql-model#19]
I am making a DB connection in Node for the first time.
I am able to connect to DB using https://github.com/mysqljs/mysql module. Then researching for models to access table data easily like I do in Lumen I found this module which is throwing this error on trying to connect s instructed.

**ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES).**

Is there something I am missing and need to install separately, I don't think there is any permission issue as I can connect to DB via same credentials using node mysql module.

**Comment by patrixgdd** [comment]
I have the same issue.

**Comment by michalkow** [comment]
I moved the project to a new repo: https://github.com/michalkow/node-mysql-backbone
I separated Model and Collection code from node-mysql library.
