### ISSUE TITLE
Mysql-model : ER_ACCESS_DENIED_ERROR

### ISSUE THREAD

**Issue by RachedM** [michalkow/node-mysql-model#20]
using the module "mysql" i get connected to my database Mysql but when i put "mysql-model" instead of "mysql" i always have a connection error with a user who has a word of mysql past. knowing that the mysql user has all the rights Grant.

Config.js
const mysql_model = require('mysql-model');
const fs = require('fs');
// Connect to my sql database
const connection = mysql_model.createConnection({
	host:'localhost',
	user:'USER', 
	password :'PASS',
	database:'DATABASE',
});

Help please.

**Comment by patrixgdd** [comment]
I have the same issue. Seems it is the common problem.
nodejs: 10.13.0
npm: 6.4.1

**Comment by patrixgdd** [comment]
temp fix:
https://github.com/michalkow/node-mysql-model/issues/9

**Comment by michalkow** [comment]
I moved the project to a new repo: https://github.com/michalkow/node-mysql-backbone
I separated Model and Collection code from node-mysql library.
