### ISSUE TITLE
Connection Pools

### ISSUE THREAD

**Issue by theRealRizeo** [michalkow/node-mysql-model#7]
Hello,

Wanted to know if it supports connection pools.

Thank you

**Comment by michalkow** [comment]
I added new branch `connection-pool`, could you test it out? Should work the same just instead `createConnection` use `createPool`(options like in [felixge/node-mysql](https://github.com/felixge/node-mysql#pooling-connections) `createPool`)

**Comment by dropdeadfu** [comment]
damn just made the changes and did a pull request instead of reading this issue first...

**Comment by michalkow** [comment]
I moved the project to a new repo: https://github.com/michalkow/node-mysql-backbone
I separated Model and Collection code from node-mysql library.
